entities:
  seaf.ba.products:
    title: Продукты или услуги
    schema:
      type: object
      patternProperties:
        "[a-zA-Z0-9_]*(\\.[a-zA-Z0-9_]*)*$":
          type: object
          properties:
            title:
              title: Наименование
              type: string
            description:
              title: Описание
              type: string
#todo нужно реализовать сущность
#            owner:
#              title: Владелец продукта
#              type: string
#              $ref: "#/$rels/seaf.ba.paries.parties"
            used_in:
              title: используется в
              type: array
              items:
                $ref: "#/$rels/seaf.ba.products.products"
            systems:
              title: Связи с АС
              type: array
              items:
                $ref: "#/$rels/components.component"
            is_channel:
              title: является каналом
              type: object
              properties: 
                type:
                  title: Тип канала
                  enum:
                    - Цифровой
                    - Физический
                    - Смешанный
                security:
                  title: Способы защиты канала
                  type: string
              required:
                - type
                - security
            status:
              title: Статус
              enum:
                - Создается
                - Используется
                - Выводится
                - В архиве
            comments:
              title: Комментарии, риски, проблемы
              type: array
              items:
                type: string
          required:
            - title
            - description
            - status
            - owner
    objects:
      products:
        route: "/"
        title: Продукт-услуга
        symbol: "prd"
