# Интеграции SEAF
entities:
  seaf.app.integrations:
    title: Интеграции
    description: Интеграция между компонентами, автоматизированными системами
    objects:
      integrations:
        route: "/"
        title: Интеграция
    schema:
      type: object
      patternProperties:
        "^[a-z0-9_\\$][a-z0-9_\\$]*(\\.[a-z0-9_\\$][a-z0-9_\\$]*)*$":
          type: object
          properties:
            title:
              title: Наименование интеграции
              type: string
            description:
              title: Описание интеграции
              type: string
            from:
              title: Источник
              description: Идентификатор компонента (или автоматизированной системы) - источника
              $ref: "#/$rels/components.component"
            to:
              title: Приемник
              description: Идентификатор компонента (или автоматизированной системы) - приемника
              $ref: "#/$rels/components.component"
            specifications:
              title: Спецификации
              description: Идентификаторы спецификаций интеграции для данной интеграции
              type: array
              minItems: 1
              items:
                title: Идентификатор спецификации
                $ref: "#/$rels/seaf.app.integration_specifications.specification"
          required:
            - title
            - description
            - from
            - to
    menu: >
      (
        [{
            "link": "/entities/seaf.app.integrations/registry", 
            "location": "SEAF-CORE/Прикладная архитектура/Реализация на ММ DocHub/Интеграции" 
        }]
      )